package id.ac.poliban.mi.sultan.customlistview;

import java.util.ArrayList;
import java.util.List;

public class CountryData {

    static List<Country> getAllCountries(){
        List<Country> data = new ArrayList<>();
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png", "Argentina", "Republik Argentina (bahasa Spanyol: República Argentina), lebih dikenal sebagai Argentina, merupakan negara Amerika Latin terbesar kedua dan negara berbahasa Spanyol terbesar di dunia. Argentina terletak di bagian selatan benua Amerika Selatan. Posisinya berada di antara Pegunungan Andes di barat dan Samudra Atlantik di selatan. Lokasi ini membuat Argentina dikenal sebagai 'negara paling selatan di selatan' (bahasa Spanyol: \"Sur del sur\"). Argentina mempunyai kawasan yang luas dan merupakan negara terbesar kedelapan di dunia sedangkan ibu kotanya Buenos Aires adalah salah satu metropolitan yang terpadat di dunia. Negara ini berbatasan dengan Paraguay dan Bolivia di sebelah utara, Brasil dan Uruguay di timur laut dan Chili di sebelah barat. Nama resminya untuk kepentingan legislatif ialah 'Negara Argentina' (Nacion Argentina)."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png", "Brasil", "Republik Federatif Brasil atau Republik Federal Brasil (bahasa Portugis: República Federativa do Brasil, bahasa Inggris: Federative Republic of Brazil, bahasa Latin: Respublica Foederativa Brasiliae) adalah negara paling besar dan paling banyak penduduknya(204.5 juta jiwa pada tahun 2017[4]) di Amerika Selatan. Negara ini merupakan negara paling timur di Benua Amerika dan berbatasan dengan Pegunungan Andes dan Samudra Atlantik. Nama Brasil diambil dari nama Kayu Brasil, sejenis kayu lokal. Brasil merupakan tempat pertanian ekstensif dan hutan hujan tropis. Sebagai bekas koloni Portugal, bahasa resmi Brasil adalah bahasa Portugis. Selain itu, Brasil juga sebagai penghasil kopi terbesar di dunia."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png", "Amerika Serikat", "Amerika Serikat, disingkat dengan AS (bahasa Inggris: United States of America/U.S.A. disingkat United States/US), atau secara umum dikenal dengan Amerika saja,[catatan 1] adalah sebuah negara republik konstitusional federal yang terdiri dari lima puluh negara bagian dan sebuah distrik federal.[7] Negara ini terletak di bagian tengah Amerika Utara, yang menjadi lokasi dari empat puluh delapan negara bagian yang saling bersebelahan, beserta distrik ibu kota Washington, D.C.. Amerika Serikat diapit oleh Samudra Pasifik dan Atlantik di sebelah barat dan timur, berbatasan dengan Kanada di sebelah utara, dan Meksiko di sebelah selatan. Dua negara bagian lainnya, yaitu Alaska dan Hawaii, terletak terpisah dari dataran utama Amerika Serikat. Negara bagian Alaska terletak di sebelah ujung barat laut Amerika Utara, berbatasan dengan Kanada di sebelah timur dan Rusia di sebelah barat, yang dipisahkan oleh Selat Bering. Sedangkan negara bagian Hawaii adalah sebuah kepulauan yang berlokasi di Samudra Pasifik. Amerika Serikat juga memiliki beberapa teritori di Pasifik dan Karibia. Dengan luas wilayah 3,79  juta mil persegi (9,83 juta km2) dan jumlah penduduk sebanyak 315 juta jiwa, Amerika Serikat merupakan negara terluas ketiga atau keempat di dunia, dan terbesar ketiga menurut jumlah penduduk. Amerika Serikat adalah salah satu negara multietnik dan multikultural di dunia. Hal tersebut muncul akibat adanya imigrasi besar-besaran dari berbagai penjuru dunia.[8] Iklim dan geografi Amerika Serikat juga sangat beragam dan negara ini menjadi tempat tinggal bagi beragam spesies."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/125px-Flag_of_Belgium_%28civil%29.svg.png", "Belgia", "Kerajaan Belgia adalah sebuah negara di Eropa bagian barat. Di sebelah utara Belgia berbatasan dengan Belanda, di sebelah timur dengan Jerman dan di sebelah selatan dengan Perancis dan Luxemburg. Sedangkan di sebelah barat Belgia berbatasan dengan Laut Utara, di seberang Britania Raya. Negara ini adalah sebuah kerajaan federal yang terdiri dari negara bagian: Flandria, Walonia dan Kota Brusel."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/125px-Flag_of_France.svg.png", "Perancis", "Republik Prancis atau Prancis (bahasa Prancis: République française, pengucapan bahasa Prancis: [ʁepyblik fʁɑ̃sɛz]) adalah sebuah negara yang teritori metropolitannya terletak di Eropa Barat dan juga memiliki berbagai pulau dan teritori seberang laut yang terletak di benua lain.[4] Prancis Metropolitan memanjang dari Laut Mediterania hingga Selat Inggris dan Laut Utara, dan dari Rhine ke Samudera Atlantik. Orang Prancis sering menyebut Prancis Metropolitan sebagai \"L'Hexagone\" (\"Heksagon\") karena bentuk geometris teritorinya. Prancis adalah sebuah republik kesatuan semi-presidensial. Ideologi utamanya tercantum dalam Deklarasi Hak Asasi Manusia dan Warga Negara.\n" +
                "\n" +
                "Prancis berbatasan dengan Belgia, Luksemburg, Jerman, Swiss, Italia, Monako, Andorra, dan Spanyol. Karena memiliki departemen seberang laut, Prancis juga berbagi perbatasan tanah dengan Brasil dan Suriname (berbatasan dengan Guyana Prancis), dan Sint Maarten (berbatasan dengan Saint-Martin). Prancis juga terhubung dengan Britania Raya oleh Terowongan Channel, yang berada di bawah Selat Inggris."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/125px-Flag_of_Luxembourg.svg.png", "Luxemburg", "Luksemburg /ˈlʌksəmbɜrɡ/ (bantuan·info) atau resminya Keharyapatihan Luksemburg (bahasa Prancis: Grand-Duché de Luxembourg, bahasa Jerman: Großherzogtum Luxemburg, bahasa Luksemburg: Groussherzogtum Lëtzebuerg) adalah sebuah negara yang tidak berbatasan dengan laut di Eropa bagian barat laut, berbatasan dengan Prancis (perbatasan panjang 73 km), Jerman (panjang perbatasan 138 km) dan Belgia (panjang perbatasan 148 km). Merupakan negara dengan luas 2.586 kilometer. Sejak 1815, Luksemburg merupakan satu satunya negara di dunia yang masih dipimpin oleh adipati atau haryapatih sebagai kepala negara."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png", "Jerman", "Republik Federal Jerman (bahasa Jerman: Bundesrepublik Deutschland) adalah negara berbentuk federasi di Eropa Barat. Negara ini memiliki posisi ekonomi dan politik yang sangat penting di Eropa maupun di dunia. Dengan luas 357.021 kilometer persegi (kira-kira dua setengah kali pulau Jawa) dan penduduk sekitar 82 juta jiwa, negara dengan 16 negara bagian (Bundesland, jamak: Bundesländer) ini menjadi anggota kunci organisasi Uni Eropa (penduduk terbanyak), penghubung transportasi barang dan jasa antarnegara sekawasan, serta menjadi negara dengan penduduk imigran ketiga terbesar di dunia.[9]\n" +
                "\n" +
                "Meskipun negara-bangsa Jerman modern baru terbentuk pada tahun 1871 seusai Perang Prancis-Prusia, satuan-satuan politik di wilayah ini telah lama memainkan posisi penting dalam era monarki di Eropa sejak penguasaan oleh Kekaisaran Romawi menjelang era modern (Masehi) hingga berakhirnya Perang Napoleon. Penyatuan wilayah Eropa Tengah pada masa Karl Yang Agung (Charlemagne), pemimpin Kerajaan Franka, pada abad ke-8 menjadi rintisan terbentuknya suatu imperium konfederatif berusia hampir 1000 tahun yang dikenal sebagai Imperium Romawi Suci. Imperium ini sangat mewarnai budaya feodal di seluruh Eropa serta menjadi pusat Reformasi gereja kristen pada abad ke-16 yang melahirkan Protestantisme. Ketika Imperium Romawi Suci dibubarkan pada tahun 1806 akibat perpecahan yang ditimbulkan oleh perang Napoleon, telah tumbuh rasa satu kebangsaan sebagai masyarakat berbahasa yang sama (bahasa Jerman). Namun, negara modern yang terbentuk kemudian tidak sanggup menyatukan cita-cita kebangsaan itu karena Austria membentuk sekutu bersama Hungaria menjadi negara terpisah dari negara Jerman modern. Pada tahun 1949, Jerman, dengan wilayah yang jauh berkurang akibat dua perang besar di Eropa, terbagi menjadi dua negara terpisah: Jerman Barat[10] dan Jerman Timur. Pemisahan ini berakhir 3 Oktober 1990 (menjadi hari nasional Jerman sekarang) ketika Jerman Timur secara resmi menyatukan diri dengan Jerman Barat."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/125px-Flag_of_Switzerland_%28Pantone%29.svg.png", "Swiss", "Swiss, secara resmi Konfederasi Swiss (Schweiz, Suisse, Svizzera, Svizra) atau dalam bahasa Latin Confoederatio Helvetica, adalah negara federal berisi 26 kanton di Eropa Tengah yang berbatasan dengan Jerman di utara, Prancis di barat, Italia di selatan, Liechtenstein dan Austria di timur. Swiss adalah negara yang sebagian besar wilayahnya terdiri dari Pegunungan Alpen. Swiss dikenal sebagai negara netral namun tetap memiliki kerja sama internasional yang kuat.\n" +
                "\n" +
                "Swiss terbagi atas 26 kanton. Enam darinya kadang-kadang dianggap sebagai \"separuh kanton\" karena berawal dari pemisahan tiga kanton, dampaknya hanya ada satu wakil dalam Dewan Negara. Ibu kota negara ini adalah Bern. Kota-kota penting lainnya adalah Zurich, kota terbesar di Swiss (yang dinobatkan sebagai kota yang memiliki kualitas hidup terbaik di dunia pada tahun 2006[5] dan 2007[6]), dan Jenewa, yang menjadi lokasi berbagai badan internasional seperti PBB, WHO, ILO, dan UNHCR.\n" +
                "\n" +
                "Swiss berbatasan dengan Jerman, Prancis, Italia, Austria, dan kerajaan kecil Liechtenstein. Masyarakat Swiss menuturkan banyak bahasa, dan terdapat empat bahasa resmi, yaitu bahasa Jerman, Prancis, Italia, dan bahasa Romansh yang kurang populer.\n" +
                "\n" +
                "Swiss kaya dengan sejarah sebagai sebuah negara yang netral tanpa memandang masa perang atau damai (dan tidak pernah terlibat dalam perang terhadap pemerintahan asing sejak tahun 1815). Oleh karena itu, Swiss dijadikan tuan rumah berbagai organisasi internasional seperti PBB yang meskipun markas besarnya ada di New York City, tetapi banyak mendirikan kantor di Swiss."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/125px-Flag_of_Italy.svg.png", "Italia", "Italia (Tentang suara ini Italia (bantuan·info)), resminya Republik Italia (bahasa Italia: Repubblica Italiana[7][8][9][10], adalah sebuah negara kesatuan republik parlementer di Eropa[catatan 1] Terletak di jantung Laut Mediterania. Italia berbatasan dengan Prancis, Swiss, Austria, Slovenia, San Marino dan Vatikan. Italia mencakup area seluas 301.338 km² (116.347 mi²), dan dipengaruhi oleh iklim sedang dan iklim mediterania. Dilihat dari bentuknya, peta Italia berbentuk seperti sepatu bot atau di Italia sering disebut lo Stivale[11][12]. Dengan jumlah penduduk mencapai 61 juta jiwa, Italia merupakan negara anggota UE keempat yang paling banyak penduduknya.\n" +
                "\n" +
                "Sejak Era Klasik, Italia sudah dihuni oleh berbagai bangsa dan peradaban. Seperti Bangsa Fenisia, Kartago, dan orang-orang Yunani kuno yang mendirikan permukiman di selatan Italia, bangsa Etruskan dan Kelt mendiami tengah dan utara Italia, serta suku Italia Kuno dan bangsa Italic yang tersebar di seluruh Semenanjung Italia dan Insular Italia (Sardinia dan Sisilia). Suku Italic atau yang dikenal sebagai Orang Latin membentuk Kerajaan Romawi yang pada akhirnya kerjaan tersebut menjadi sebuah republik yang berhasil menaklukkan dan mengasimilasi peradaban terdekat lainnya. Roma akhirnya muncul sebagai kekuatan dominan di cekungan mediterania, berhasil menaklukkan sebagian besar dunia kuno dan menjadi pusat kebudayaan, politik dan keagamaan terkemuka di peradaban Barat. Peninggalan Kekaisaran Romawi tersebar luas dan dapat dilihat dalam saluran distribusi global hukum sipil, pemerintahan republik, Kekristenan dan tulisan Latin.\n" +
                "\n" +
                "Selama Abad Pertengahan, Italia mengalami keruntuhan sosiopolitik di tengah invasi barbar yang merugikan, namun pada abad ke-11 banyak negara-kota dan republik maritim Italia yang bangkit untuk mencapai kemakmuran melalui pelayaran, perdagangan, dan perbankan, meletakkan dasar bagi kapistalisme modern[13]. Statelets merdeka[catatan 2], yang bertindak sebagai pusat perdagangan utama Eropa dengan Asia dan Timur Dekat, menikmati tingkat demokrasi dan kekayaan yang lebih besar dibandingkan dengan monarki feodal yang berkonsolidasi di seluruh Eropa pada saat itu. Sebagian besar Italia Tengah tetap berada di bawah kendali Negara Gereja yang bersifat teokratis, sementara Italia Selatan feodal sampai abad ke-19, sebagai hasil suksesi penaklukan Bizantium, Arab, Norman, Spanyol, dan Bourbon di wilayah ini.[14]"));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png", "Spanyol", "Spanyol (bahasa Spanyol: España [esˈpaɲa] ( simak)), secara resmi dikenal dengan sebutan Kerajaan Spanyol (bahasa Spanyol: Reino de España) adalah sebuah negara di Eropa barat daya yang, bersama Portugal, terdapat di Semenanjung Iberia. Batas darat Spanyol dengan Eropa adalah Pegunungan Pirenia dengan Prancis dan Andorra. Wilayahnya terdiri dari kota Ceuta dan Melilla di Afrika Utara, Kepulauan Canary di Samudra Atlantik, dan berbagai pulau di Laut Tengah.\n" +
                "\n" +
                "Wilayah Spanyol juga termasuk Kepulauan Balearic di Mediterania, Kepulauan Canary di Samudera Atlantik lepas pantai Afrika, dan dua kota otonom di Afrika Utara, Ceuta dan Melilla, yang berbatasan Maroko, ditambah Alboran, Kepulauan Chafarinas, Alhucemas, Vélez de la Gomera dan pulau kecil lainnya termasuk Perejil. Selain itu, kota Llívia adalah eksklave Spanyol terletak di dalam wilayah Prancis. Dengan luas 505.992 kilometer persegi (195.365 mil persegi), Spanyol adalah negara terbesar kedua di Eropa Barat dan Uni Eropa dan negara terbesar kelima di Eropa."));

        return data;
    }
}
